apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-deployment
  namespace: food-dev
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name:  backend-pod
      namespace: food-dev
      labels:
        app: backend
    spec:
      containers:
      - name: foodapp-backend
        image: vishnuvardhan225/food-backend:latest
        ports:
        - containerPort: 4000
        env:
          - name: MONGO_URL
            value: "mongodb://admin:password@mongo-service:27017/fooddb?authSource=admin"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password"
